version = 0.1
[default.deploy.parameters]
stack_name = "stepfuntionimplementation"
resolve_s3 = true
s3_prefix = "stepfuntionimplementation"
region = "ap-south-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
